<a href="https://colab.research.google.com/github/rnterrors404/Oculus_ai/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating a single dimensional array

In [ ]:
a= [7,8,6,2]
print("a = ", a)

a =  [7, 8, 6, 2]


creating a two dimensional array

In [ ]:
A= [[3,6,7,9],[3,5,6,-2],[-9,4,1,7]]
print("A =", A)

A = [[3, 6, 7, 9], [3, 5, 6, -2], [-9, 4, 1, 7]]


creating a two dimensional array


In [ ]:
import numpy as np

a= np.array([[7],[8],[8],[2]])
print("a =", a)

A=np.array([[3,6,7,9],[3,5,6,-2],[-9,4,1,7]])
print("A =", A)

a = [[7]
 [8]
 [8]
 [2]]
A = [[ 3  6  7  9]
 [ 3  5  6 -2]
 [-9  4  1  7]]


creating array and matrix

In [ ]:
import numpy as np 
a= np.array([[7],[8],[8],[2]])
print("a =", a)

A=np.matrix([[3,6,7,9],[3,5,6,-2],[-9,4,1,7]])
print("A =", A)

a = [[7]
 [8]
 [8]
 [2]]
A = [[ 3  6  7  9]
 [ 3  5  6 -2]
 [-9  4  1  7]]


creating matrix and doing arithmetic operations

In [ ]:
import numpy as np
A = np.matrix([[2, 0], [-9, -6]])
B = np.matrix([[0, 2], [4, -7]])
C = A + B
print("A+B =", C)
C = A - B
print("A-B =", C)
C = A * B
print("A*B =", C)

A+B = [[  2   2]
 [ -5 -13]]
A-B = [[  2  -2]
 [-13   1]]
A*B = [[  0   4]
 [-24  24]]


doing multiplication in normal way and by using the function and checking the difference

In [ ]:

import numpy as np
A = np.matrix([[2, 0], [-9, -6]])
B = np.matrix([[0, 2], [4, -7]])
C= A + B
print("A+B =", C)
C = A - B

print("A-B =", C)
C = A * B

print("A*B =", C) # Not Working!, only elementwise Multiplication!
#Working Alternative 1

C = A.dot(B)
print("A*B =", C)
#Working Alternative 2

C = np.dot(A,B)
print("A*B =", C)
#Working Alternative 3

C = np.mat(A) * np.mat(B)
print("A*B =", C)
#Working Alternative 4

C = np.matmul(A,B)
print("A*B =", C)

A+B = [[  2   2]
 [ -5 -13]]
A-B = [[  2  -2]
 [-13   1]]
A*B = [[  0   4]
 [-24  24]]
A*B = [[  0   4]
 [-24  24]]
A*B = [[  0   4]
 [-24  24]]
A*B = [[  0   4]
 [-24  24]]
A*B = [[  0   4]
 [-24  24]]


checking the conditions of multiplication using function

In [ ]:

import numpy as np
A = np.array([[2, 6, 4], [5, 7, 7],[4, 9, 1]])
B = np.array([[2, 4, 4, 5], [5, 6, 8, 9],[8, 9, 1, 4]])
C = np.array([[2], [3],[4]])
D = np.array([[2, 3, 4]])
M = np.matmul(A,B)
print("M=", M)

#M = np.matmul(B,A) # Not Working!

M = np.matmul(A,C)
print("M=", M)
print("M=", M)

M = np.matmul(D,C)
print("M=", M)

M= [[ 66  80  60  80]
 [101 125  83 116]
 [ 61  79  89 105]]
M= [[38]
 [59]
 [39]]
M= [[38]
 [59]
 [39]]
M= [[29]]


creating an array and doing the transpose of it

In [ ]:

import numpy as np
A = np.array([[2, 4, 8, 3], [6, 9, -2, 1],[7, -8, 12, 13]])
print("A="); print(A)
Atr = np.transpose(A)
print("Transpose of A="); print(Atr)
B = np.array([[1, 5], [4, 5],[3, 2],[7, 8]])
print("B="); print(B)
Btr = np.transpose(B)
print("Transpose of B="); print(Btr)
     

A=
[[ 2  4  8  3]
 [ 6  9 -2  1]
 [ 7 -8 12 13]]
Transpose of A=
[[ 2  6  7]
 [ 4  9 -8]
 [ 8 -2 12]
 [ 3  1 13]]
B=
[[1 5]
 [4 5]
 [3 2]
 [7 8]]
Transpose of B=
[[1 4 3 7]
 [5 5 2 8]]


  creating an array and finding the determinant of it using function 

In [ ]:

import numpy as np
import numpy.linalg as la
A = np.array([[2, 3], [4, 5]])
Adet = la.det(A)
print(Adet)
B = np.array([[-2, 4, 1],[3, 2, -6],[0, 5, -3]])
Bdet = la.det(B)
print(Bdet)

-2.0
3.000000000000001


creating an array and finding the inverse of it using function

In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[2, 3], 
[4, 5]])
Ainv = la.inv(A)
print(Adet)
B = np.array([[-2, 4, 1],
[3, 2, -6],
[2, 5, -3]])
Binv = la.inv(B)
print(Binv)

-2.0
[[-0.48979592 -0.34693878  0.53061224]
 [ 0.06122449 -0.08163265  0.18367347]
 [-0.2244898  -0.36734694  0.32653061]]


creating an array and finding the eigen value of it using function

In [ ]:

import numpy as np
import numpy.linalg as la
A = np.array([[0, 2], [-3, -4]])
Aeig, v = la.eig(A)
print(Aeig)
     

[-2.+1.41421356j -2.-1.41421356j]


AB != BA

In [ ]:

import numpy as np
A = np.array([[1, 0], [-3, -4]])
B = np.array([[0, 1], [4, -3]])
C = np.array([[1, 1], [2, -6]])
print("AB Not Equal BA")
L = np.matmul(A,B)
print("L=");print(L)
R = np.matmul(B,A)
print("R=");print(R)
print("A(BC) = (AB)C")
L = np.matmul(A,np.matmul(B,C))
print("L=");print(L)
R = np.matmul(np.matmul(A,B),C)
print("R=");print(R)

AB Not Equal BA
L=
[[  0   1]
 [-16   9]]
R=
[[-3 -4]
 [13 12]]
A(BC) = (AB)C
L=
[[  2  -6]
 [  2 -70]]
R=
[[  2  -6]
 [  2 -70]]


(A+B)C = AC + BC

In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 0], [-3, -4]])
B = np.array([[0, 1], [4, -3]])
C = np.array([[1, 1], [2, -6]])
print("(A+B)C = AC + BC")
L = np.matmul(A+B,C)
print("L=");print(L)
R = np.matmul(A,C) + np.matmul(B,C)
print("R=");print(R)
print("AA^(-1) = A^(-1)A = I")
L = np.matmul(A, la.inv(A))
print("L=");print(L)
R = np.matmul(la.inv(A),A)
print("R=");print(R)

(A+B)C = AC + BC
L=
[[  3  -5]
 [-13  43]]
R=
[[  3  -5]
 [-13  43]]
AA^(-1) = A^(-1)A = I
L=
[[1. 0.]
 [0. 1.]]
R=
[[1. 0.]
 [0. 1.]]


creating an array doing an inverse of it and then doing the multiplication of the matix using the function

In [ ]:

import numpy as np
import numpy.linalg as la
A = np.array([[2, 3], [4, 5]])
b = np.array([[5], [7]])
Ainv = la.inv(A)
x = Ainv.dot(b)
print(x)

[[-2.]
 [ 3.]]


doing the same thing using the built-in function

In [ ]:

import numpy as np
A = np.array([[2, 3], [4, 5]])
b = np.array([[5], [7]])
x = np.linalg.solve(A, b)
print(x)
     

[[-2.]
 [ 3.]]


using the least square method 

In [ ]:

import numpy as np
A = np.array([[2, 3], [4, 5],[8, 9]])
b = np.array([[6],[7],[0]])
x = np.linalg.lstsq(A, b, rcond=None)[0]
print(x)

[[-10.60714286]
 [  9.5       ]]
